module.exports = {
    private_key: `-----BEGIN RSA PRIVATE KEY-----
    MIIBOwIBAAJBALgfQox9bJWW0n412JLTkpHIqyQQASXI0NizVpsk4tht9DxYPy2/
    rXBJBNasvEE3Kk7cjCXCtGC6BXIhXDKCFSECAwEAAQJAP7fRt/zPzxTa04Ke6HD/
    kCP51gkT3JeabuPhXN9vAaa08BjYRSu9/EFF1EIJIWCsWe7Kk73ECAuvYsvK4Bpg
    gQIhAOky/vHtoXv+5LGkKGfv4EYErjSPY5Z0FBDqbBq/X7htAiEAyh/bx+ZnqVxz
    YaxVOOsZg3V9TbdTvd6+y0e9aK+qhwUCIQCGAUP3ifIt6r9IRWjisTlTgwUINw2n
    O3T8c3lDtY0v0QIhAJHEqBxibiAWLKAkSNHju2KzOMrzi9FC8xZnhpIZHkKBAiBJ
    IKCmaTeLlpFE3UyfLvqdSWOzawXD+Wwo1MagFs1+FQ==
    -----END RSA PRIVATE KEY-----`
}